-- ==========================================================
-- AMAZON FASHION SALES ANALYSIS
-- FILE: 06_Promotion_Analysis.sql
--
-- Objective:
-- Analyze the impact of promotional offers on customer
-- purchasing behavior, revenue generation, and order volume.
-- ==========================================================

USE amazon_sales;

-- ----------------------------------------------------------
-- 1. Orders by Promotion Usage
-- Business Question:
-- How many customer orders were placed with and without
-- promotional offers?
-- ----------------------------------------------------------

SELECT
	Promotion_Used,
    COUNT(DISTINCT `Order ID`) AS Total_Orders
FROM amazon_sales_data
GROUP BY Promotion_Used
ORDER BY Total_Orders DESC;

-- ----------------------------------------------------------
-- 2. Revenue by Promotion Usage
-- Business Question:
-- How much revenue was generated from promoted and
-- non-promoted orders?
-- ----------------------------------------------------------

SELECT
	Promotion_Used,
    COUNT(DISTINCT `Order ID`) AS Total_Orders,
    SUM(Qty) AS Units_Sold,
    ROUND(SUM(Amount),2) AS Revenue
FROM amazon_sales_data
GROUP BY Promotion_Used
ORDER BY Revenue DESC;

-- ----------------------------------------------------------
-- 3. Promotion Revenue Contribution
-- Business Question:
-- What percentage of total revenue is generated by
-- promoted and non-promoted orders?
-- ----------------------------------------------------------

SELECT
    Promotion_Used,
    ROUND(SUM(Amount),2) AS Revenue,
    ROUND(
        SUM(Amount) * 100 /
        (SELECT SUM(Amount) FROM amazon_sales_data),
        2
    ) AS Revenue_Percentage
FROM amazon_sales_data
GROUP BY Promotion_Used
ORDER BY Revenue DESC;

-- ----------------------------------------------------------
-- 4. Average Order Value by Promotion Usage
-- Business Question:
-- Does promotion usage influence the average customer
-- order value?
-- ----------------------------------------------------------

SELECT
    Promotion_Used,
    ROUND(
        SUM(Amount) /
        COUNT(DISTINCT `Order ID`),
        2
    ) AS Average_Order_Value
FROM amazon_sales_data
GROUP BY Promotion_Used;

-- ----------------------------------------------------------
-- 5. Average Units per Order by Promotion Usage
-- Business Question:
-- Do promotions encourage customers to purchase more
-- items per order?
-- ----------------------------------------------------------

SELECT
    Promotion_Used,
    ROUND(
        SUM(Qty) /
        COUNT(DISTINCT `Order ID`),
        2
    ) AS Average_Units_Per_Order
FROM amazon_sales_data
GROUP BY Promotion_Used;

-- ==========================================================
-- End of File: 06_Promotion_Analysis.sql
-- ==========================================================